name: CI/CD Pipeline

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        directory: ['client', 'server']
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Dependencies
      run: npm install
      working-directory: ${{ matrix.directory }}
      
    - name: Run Tests
      run: npm test
      working-directory: ${{ matrix.directory }}
    
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # or your preferred region
    
    # Add your steps to deploy to AWS
    - name: Deploy to AWS
      run: |
        cd server
        # Add your AWS deployment commands here
